/**
 * Military-grade encryption using Web Crypto API (AES-GCM 256-bit).
 * This provides Zero-Knowledge privacy: the key is derived from the user's PIN
 * and never stored on disk.
 */

const ALGORITHM = "AES-GCM";
const KEY_LENGTH = 256;
const ITERATIONS = 100000;

/**
 * Derives a cryptographic key from a user-provided PIN.
 */
async function deriveKey(pin: string, salt: Uint8Array): Promise<CryptoKey> {
    const encoder = new TextEncoder();
    const pinData = encoder.encode(pin);

    const baseKey = await window.crypto.subtle.importKey(
        "raw",
        pinData,
        "PBKDF2",
        false,
        ["deriveKey"]
    );

    return window.crypto.subtle.deriveKey(
        {
            name: "PBKDF2",
            salt: salt as BufferSource,
            iterations: ITERATIONS,
            hash: "SHA-256",
        },
        baseKey,
        { name: ALGORITHM, length: KEY_LENGTH },
        false,
        ["encrypt", "decrypt"]
    );
}

/**
 * Encrypts data using a PIN.
 * Returns a base64 string containing: salt (16b) + iv (12b) + ciphertext
 */
export async function encryptData(data: string, pin: string): Promise<string> {
    const encoder = new TextEncoder();
    const encodedData = encoder.encode(data);

    // Generate salt and IV
    const salt = window.crypto.getRandomValues(new Uint8Array(16));
    const iv = window.crypto.getRandomValues(new Uint8Array(12));

    const key = await deriveKey(pin, salt);

    const ciphertext = await window.crypto.subtle.encrypt(
        { name: ALGORITHM, iv },
        key,
        encodedData
    );

    // Combine result for storage
    const combined = new Uint8Array(salt.length + iv.length + ciphertext.byteLength);
    combined.set(salt, 0);
    combined.set(iv, salt.length);
    combined.set(new Uint8Array(ciphertext), salt.length + iv.length);

    // Return as Base64 string
    return btoa(String.fromCharCode(...combined));
}

/**
 * Decrypts data using a PIN.
 * Expects a base64 string generated by encryptData.
 */
export async function decryptData(encryptedBase64: string, pin: string): Promise<string> {
    try {
        const decoded = new Uint8Array(
            atob(encryptedBase64).split("").map(c => c.charCodeAt(0))
        );

        // Extract components
        const salt = decoded.slice(0, 16);
        const iv = decoded.slice(16, 28);
        const ciphertext = decoded.slice(28);

        const key = await deriveKey(pin, salt);

        const decrypted = await window.crypto.subtle.decrypt(
            { name: ALGORITHM, iv },
            key,
            ciphertext
        );

        return new TextDecoder().decode(decrypted);
    } catch (error) {
        console.error("Decryption failed:", error);
        throw new Error("Wrong PIN or corrupted data");
    }
}
